[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F565A2E250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/36cd86b3fbbd93098df7660fb90d752f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F565A2E360>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/36cd86b3fbbd93098df7660fb90d752f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F565A2DE10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/36cd86b3fbbd93098df7660fb90d752f