[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F565A2E580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e45aa6e57f7d1120d4514c032ae52cbd
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F565A2C8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e45aa6e57f7d1120d4514c032ae52cbd
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F565A2C270>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e45aa6e57f7d1120d4514c032ae52cbd