[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=56920): Read timed out. (read timeout=120)")': /session/b6fe714bc3c7199a29f8b27023f4224e/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=56920): Read timed out. (read timeout=120)")': /session/b6fe714bc3c7199a29f8b27023f4224e/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=56920): Read timed out. (read timeout=120)")': /session/b6fe714bc3c7199a29f8b27023f4224e/url