{"uuid": "317b14b1-0e27-4a6d-aefd-2a49df14702b", "children": ["5e95409d-a8ec-499a-9646-f09e915a1436"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: JavaScript code failed\nfrom unknown command: 'Runtime.evaluate' wasn't found\n  (Session info: chrome=135.0.7049.96)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6E3411F55+78133]\n\tGetHandleVerifier [0x00007FF6E3411FB0+78224]\n\t(No symbol) [0x00007FF6E31D91BA]\n\t(No symbol) [0x00007FF6E31C5930]\n\t(No symbol) [0x00007FF6E31C411B]\n\t(No symbol) [0x00007FF6E31C492F]\n\t(No symbol) [0x00007FF6E31EFF7B]\n\t(No symbol) [0x00007FF6E31E35D0]\n\t(No symbol) [0x00007FF6E31E3472]\n\t(No symbol) [0x00007FF6E31B5061]\n\t(No symbol) [0x00007FF6E31B3003]\n\t(No symbol) [0x00007FF6E3297301]\n\t(No symbol) [0x00007FF6E325715A]\n\t(No symbol) [0x00007FF6E327F21F]\n\t(No symbol) [0x00007FF6E3256F33]\n\t(No symbol) [0x00007FF6E3220358]\n\t(No symbol) [0x00007FF6E32210C3]\n\tGetHandleVerifier [0x00007FF6E36DBA8D+3001453]\n\tGetHandleVerifier [0x00007FF6E36D5E72+2977874]\n\tGetHandleVerifier [0x00007FF6E36F497D+3103581]\n\tGetHandleVerifier [0x00007FF6E342C7EA+186826]\n\tGetHandleVerifier [0x00007FF6E34343FF+218591]\n\tGetHandleVerifier [0x00007FF6E3419D94+110452]\n\tGetHandleVerifier [0x00007FF6E3419F42+110882]\n\tGetHandleVerifier [0x00007FF6E3400379+5465]\n\tBaseThreadInitThunk [0x00007FFCA63EE8D7+23]\n\tRtlUserThreadStart [0x00007FFCA72114FC+44]\n\n", "trace": "  File \"C:\\Users\\usmaan.arshad\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\usmaan.arshad\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\usmaan.arshad\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\usmaan.arshad\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\usmaan.arshad\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\usmaan.arshad\\PycharmProjects\\PythonProject\\tests\\Additional_Functionalities\\test_qp_display_in_account_preview.py\", line 16, in driver\n    driver.maximize_window()\n    ~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\usmaan.arshad\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 536, in maximize_window\n    self.execute(command, None)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"C:\\Users\\usmaan.arshad\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\usmaan.arshad\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1745399874791, "stop": 1745399876916}], "start": 1745399874791, "stop": 1745399879836}