{"name": "test_dialog_display_in_mapping", "status": "skipped", "statusDetails": {"message": "Skipped: Skipping test due to unexpected login error: ReadTimeoutError", "trace": "('C:\\\\Users\\\\usmaan.arshad\\\\PycharmProjects\\\\PythonProject\\\\tests\\\\Sync_Legacy_Records\\\\test_cancel_option_in_dialog_box_in_mapping.py', 54, 'Skipped: Skipping test due to unexpected login error: ReadTimeoutError')"}, "start": 1745328856489, "stop": 1745328986782, "uuid": "b23e6ea9-eaf3-49c3-9af2-4a7998184780", "historyId": "86ff9cbb1d9cf71a542e5d42f79da91f", "testCaseId": "86ff9cbb1d9cf71a542e5d42f79da91f", "fullName": "tests.Sync_Legacy_Records.test_cancel_option_in_dialog_box_in_mapping#test_dialog_display_in_mapping", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Confirmation Dialog"}, {"name": "story", "value": "Test 'Cancel' option in the confirmation dialog."}, {"name": "tag", "value": "P1"}, {"name": "tag", "value": "Skipped"}, {"name": "parentSuite", "value": "tests.Sync_Legacy_Records"}, {"name": "suite", "value": "test_cancel_option_in_dialog_box_in_mapping"}, {"name": "host", "value": "RT-LT-597"}, {"name": "thread", "value": "9988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Sync_Legacy_Records.test_cancel_option_in_dialog_box_in_mapping"}]}